//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTScore
    {
        public int actID { get; set; }
        public int studentID { get; set; }
        public Nullable<byte> attmepted { get; set; }
        public Nullable<System.DateTime> dateAttempted { get; set; }
        public Nullable<byte> compositeScore { get; set; }
        public Nullable<byte> englishScore { get; set; }
        public Nullable<byte> mathScore { get; set; }
        public Nullable<byte> readingScore { get; set; }
        public Nullable<byte> scienceScore { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
