//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contactID { get; set; }
        public int studentID { get; set; }
        public int advisorID { get; set; }
        public int schoolID { get; set; }
        public byte serviceMethodID { get; set; }
        public Nullable<short> serviceID { get; set; }
        public Nullable<byte> parentServiceID { get; set; }
        public Nullable<System.DateTime> serviceDate { get; set; }
        public Nullable<short> serviceMinutes { get; set; }
        public string parentName { get; set; }
        public string details { get; set; }
        public bool parentOnly { get; set; }
        public bool serviceIneligible { get; set; }
        public bool compass { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Advisor Advisor { get; set; }
        public virtual ParentServiceCode ParentServiceCode { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceMethod ServiceMethod { get; set; }
    }
}
