//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearUp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GearUpDBEntities : DbContext
    {
        public GearUpDBEntities()
            : base("name=GearUpDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTScore> ACTScores { get; set; }
        public virtual DbSet<Advisor> Advisors { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<CollegeStatu> CollegeStatus { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<CreditRecoveryClass> CreditRecoveryClasses { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<ParentServiceCode> ParentServiceCodes { get; set; }
        public virtual DbSet<PersonEmployer> PersonEmployers { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<RigorClass> RigorClasses { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Scholarship> Scholarships { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SeniorPaperwork> SeniorPaperworks { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceCode> ServiceCodes { get; set; }
        public virtual DbSet<ServiceMethod> ServiceMethods { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentCollege> StudentColleges { get; set; }
        public virtual DbSet<StudentScholarship> StudentScholarships { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
    }
}
