//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int scheduleID { get; set; }
        public int classID { get; set; }
        public int termID { get; set; }
        public Nullable<byte> period { get; set; }
        public Nullable<int> crPointsNeeded { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Term Term { get; set; }
    }
}
