//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ACTScores = new HashSet<ACTScore>();
            this.Contacts = new HashSet<Contact>();
            this.CreditRecoveryClasses = new HashSet<CreditRecoveryClass>();
            this.Notes = new HashSet<Note>();
            this.PersonEmployers = new HashSet<PersonEmployer>();
            this.RigorClasses = new HashSet<RigorClass>();
            this.SeniorPaperworks = new HashSet<SeniorPaperwork>();
            this.StudentScholarships = new HashSet<StudentScholarship>();
            this.StudentColleges = new HashSet<StudentCollege>();
            this.Surveys = new HashSet<Survey>();
            this.Terms = new HashSet<Term>();
        }
    
        public int studentID { get; set; }
        public int schoolID { get; set; }
        public Nullable<int> raceID { get; set; }
        public Nullable<int> advisorID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<short> classOf { get; set; }
        public Nullable<bool> hispanic { get; set; }
        public Nullable<bool> iep { get; set; }
        public Nullable<bool> lep { get; set; }
        public Nullable<bool> hasSiblings { get; set; }
        public string siblingNames { get; set; }
        public Nullable<bool> collegeGreenLight { get; set; }
        public Nullable<bool> lifePlanStatus { get; set; }
        public string careerGoal1 { get; set; }
        public string careerGoal2 { get; set; }
        public string mathLevel { get; set; }
        public string parentsPreferredLanguage { get; set; }
        public Nullable<bool> undocumented { get; set; }
        public Nullable<int> compassStudentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTScore> ACTScores { get; set; }
        public virtual Advisor Advisor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditRecoveryClass> CreditRecoveryClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonEmployer> PersonEmployers { get; set; }
        public virtual Race Race { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RigorClass> RigorClasses { get; set; }
        public virtual School School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeniorPaperwork> SeniorPaperworks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentScholarship> StudentScholarships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCollege> StudentColleges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Survey> Surveys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Term> Terms { get; set; }
    }
}
