//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCollege
    {
        public int studentCollegeID { get; set; }
        public int studentID { get; set; }
        public int schoolID { get; set; }
        public Nullable<byte> preferenceOrder { get; set; }
        public byte collegeStatusID { get; set; }
    
        public virtual CollegeStatu CollegeStatu { get; set; }
        public virtual School School { get; set; }
        public virtual Student Student { get; set; }
    }
}
