//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public int surveyID { get; set; }
        public int studentID { get; set; }
        public bool studentCompleted { get; set; }
        public bool parentCompleted { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
