//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Term()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int termID { get; set; }
        public int studentID { get; set; }
        public Nullable<System.DateTime> year { get; set; }
        public Nullable<byte> term1 { get; set; }
        public Nullable<byte> absences { get; set; }
        public Nullable<short> gpaPoints { get; set; }
        public Nullable<short> gpaHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual Student Student { get; set; }
    }
}
